apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: kube-system
spec:
  selector:
    app: backend
  ports:
    - name: http  # ✅ Required for multiple ports
      protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
