apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: mern-namespace
spec:
  selector:
    app: backend
  ports:
    - port: 80          # The port exposed by the service
      targetPort: 5000   # The port on the backend pod

