apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: kube-system
spec:
  selector:  # ✅ Corrected indentation
    app: frontend
  type: LoadBalancer
  ports:
    - name: http  # ✅ Recommended for multiple ports
      protocol: TCP
      port: 80
      targetPort: 3000
