apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mern-namespace
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" 
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
